image: nixos/latest
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
sources:
  - https://git.sr.ht/~jack/mudcore
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - build: |
      cd mudcore
      nix build -L --no-link
triggers:
  - condition: failure
    action: email
    to: jack@jackkelly.name
